name: scr
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10
  - numpy
  - openai
  - transformers
  - datasets
  - matplotlib
  - pandas
  - faiss-gpu
  - pytorch
  - scikit-learn
  - h5py
  - pip:
    - nltk
    - accelerate
prefix: /home/user/anaconda3/envs/scr
